#pragma once

#if defined(DMGUI_IMPLEMENTATION)

#include <new>
#define dmguiMalloc(size) ::operator new(size)
#define dmguiFree(ptr) ::operator delete(ptr)

#include <unordered_map>
#define dmgui_unordered_map_t std::unordered_map

#include <vector>
#define dmgui_vector_t std::vector

#endif

typedef enum DMGUI_STYLE
{
    DMGUI_STYLE_NONE,
    DMGUI_STYLE_MAIN,
    DMGUI_STYLE_FRAME,
    DMGUI_STYLE_OVERLAY,
    DMGUI_STYLE_BORDER,

    DMGUI_STYLE_HEADER,
    DMGUI_STYLE_HEADER_BUTTON,
    DMGUI_STYLE_HEADER_BUTTON_HOVER,
    DMGUI_STYLE_HEADER_BUTTON_PRESS,
    DMGUI_STYLE_HEADER_BUTTON_SELECT,
    DMGUI_STYLE_HEADER_BUTTON_DISABLE,

    DMGUI_STYLE_TAB,
    DMGUI_STYLE_TAB_HOVER,
    DMGUI_STYLE_TAB_PRESS,
    DMGUI_STYLE_TAB_SELECT,
    DMGUI_STYLE_TAB_DISABLE,

    DMGUI_STYLE_BUTTON,
    DMGUI_STYLE_BUTTON_HOVER,
    DMGUI_STYLE_BUTTON_PRESS,
    DMGUI_STYLE_BUTTON_SELECT,
    DMGUI_STYLE_BUTTON_DISABLE,

    DMGUI_STYLE_HANDLE,
    DMGUI_STYLE_HANDLE_HOVER,
    DMGUI_STYLE_HANDLE_PRESS,
    DMGUI_STYLE_HANDLE_SELECT,
    DMGUI_STYLE_HANDLE_DISABLE,

    DMGUI_STYLE_GUTTER,

    DMGUI_STYLE_ACCENT1,
    DMGUI_STYLE_ACCENT2,
    DMGUI_STYLE_UNUSED1,
    DMGUI_STYLE_UNUSED2,
    DMGUI_STYLE_UNUSED3,

    DMGUI_STYLE_COUNT
} DMGUI_STYLE;
